#!/usr/bin/env bash
set -e

echo Installing madup...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
MADUP_DIR=${MADUP_DIR-"$BASE_DIR/.madup"}
MADUP_BIN_DIR="$MADUP_DIR/bin"
MADUP_MAN_DIR="$MADUP_DIR/share/man/man1"

BIN_URL="https://raw.githubusercontent.com/Generative-Labs/madara-and-dojo/main/madup/madup"
BIN_PATH="$MADUP_BIN_DIR/madup"


# Create the .madup bin directory and madup binary if it doesn't exist.
mkdir -p $MADUP_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Create the man directory for future man files if it doesn't exist.
mkdir -p $MADUP_MAN_DIR

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "madup: could not detect shell, manually add ${MADUP_BIN_DIR} to your PATH."
    exit 1
esac

# Only add madup if it isn't already in PATH.
if [[ ":$PATH:" != *":${MADUP_BIN_DIR}:"* ]]; then
    # Add the madup directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$MADUP_BIN_DIR\"" >> $PROFILE
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added madup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use madup."
echo "Then, simply run 'madup' to install Madup."
