#!/usr/bin/env bash
set -e

#!/bin/bash
BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
MADUP_DIR=${MADUP_DIR-"$BASE_DIR/.madup"}

function install_madara() {
    os=$(uname -s | awk '{ print tolower($0) }')
    machine=$(uname -m)

    case "$os" in
      "darwin")
        os="apple-darwin"
        ;;
      "linux")
        os="unknown-linux-gnu"
        ;;
      *)
        echo "Unknown OS"
        exit 1
        ;;
    esac

    case "$machine" in
      "x86_64")
        machine="x86_64"
        ;;
      "arm64"*)
        machine="aarch64"
        ;;
      *)
        echo "Unknown machine"
        exit 1
        ;;
    esac

    PkgName="${machine}-${os}-madara"

    curl -LO "https://github.com/Generative-Labs/madara-and-dojo/releases/latest/download/${PkgName}.zip"

    mkdir -p ${MADUP_DIR}

    unzip ${PkgName}.zip -d ${MADUP_DIR}
    mv ${MADUP_DIR}/${PkgName}/madara ${MADUP_DIR}/bin
}

function update_config() {
    # Add your update code here
    awk '/rpc_url =/ {$0="rpc_url = \"http://localhost:9944/\""}1' Scarb.toml > temp && mv temp Scarb.toml
    awk '/# Default account for katana with seed = 0/ {$0="# Default account for madara 0x3"}1' Scarb.toml > temp && mv temp Scarb.toml
    awk '/account_address =/ {$0="account_address = \"0x3\""}1' Scarb.toml > temp && mv temp Scarb.toml
    awk '/private_key =/ {$0="private_key = \"0x00c1cf1490de1352865301bb8705143f3ef938f97fdf892f1090dcb5ac7bcd1d\""}1' Scarb.toml > temp && mv temp Scarb.toml
}

function usage() {
    echo "Usage: $0 [init|update-sozo-config|install-madara]"
    echo "init:   Initialize the madup"
    echo "install-madara: Install madara"
    echo "update-sozo-config: Update the sozo config"
    exit 1
}

if [ "$#" -eq 0 ]; then
    usage
fi

case $1 in
    init)
        echo "Initializing the dojoup..."
        # Add your init code here
        curl -L https://install.dojoengine.org | bash

        dojoup

        echo "Install madara..."
        install_madara
        ;;
    install-madara)
        echo "Install madara..."
        install_madara
        ;;
    update-sozo-config)
        echo "Updating the Scarb.toml ..."
        # Add your update code here

        update_config
        ;;
    *)
        usage
        ;;
esac
